import type { Metadata } from "next";
import PageLoader from "@/components/PageLoader";
import { LoaderProvider } from "@/components/hero/LoaderContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LoaderProvider>
          <PageLoader />
          {children}
        </LoaderProvider>
      </body>
    </html>
  );
}
